### ISSUE TITLE
The language server should exit if the parent process dies

### ISSUE THREAD

**Issue by kaloyan-raev** [felixfbecker/php-language-server#106]
According to LSP:

> If the parent process is not alive then the server should exit (see exit notification) its process.

Currently if the parent process exits without sending the exit notification, the process of the language server goes in a high CPU loop. While experimenting, I often fall in this situation and have to kill the zombie processes manually.

**Comment by felixfbecker** [comment]
If the LS is spawned as a non-detached child process, the OS should handle this. Afaik we have no other option really besides polling the PID, which is a no-go.

**Comment by kaloyan-raev** [comment]
> Afaik we have no other option really besides polling the PID, which is a no-go.

Why not? The language server start cycling indefinitely in some loop when the parent dies. What is the language server doing in this loop? Perhaps, this is the perfect place to check if the parent process id is still alive.

**Comment by felixfbecker** [comment]
It is in the event loop of course. Polling would mean you do a `setInteral` so every nth second any event in the event queue would get deferred because we are polling the PID. But how can that even happen in the first place? Are you using VS Code? Because vscode-php-intellisense spawns the LS as a _child process_, which means it should exit as soon as the parent process exits. Maybe that doesn't happen because the event loop is active and we don't have a SIGTERM handler?

**Comment by kaloyan-raev** [comment]
Yes, this happens when using VSCode too. BTW, I am with a quite old version of the vscode-php-intellisense extension. It also happens in my simple test environment when using the Typefox Java binding as a client.

Perhaps, the OS matters. I am on Linux. What OS do you use?

**Comment by felixfbecker** [comment]
I am on Windows, and using the `uri-fix` branch, which includes the (windows-breaking) command line argument changes.

Here is the documentation of `detached`, which we _do not_ use:
https://nodejs.org/api/child_process.html#child_process_options_detached

I really wonder how a parent process can exit with it's child process continuing to run without using `detached`? Should be impossible, no matter the OS

**Comment by mniewrzal** [comment]
I have the same issue and I think I know what can cause this problem. Like @kaloyan-raev  I'm using Eclipse PDT to code/debug LS. When LS code will trigger breakpoint (Eclipse PDT will catch it) and VS Code will be closed before this breakpoint will be released then php child process is not killed and its running infinite loop. I think this isn't real user case but someone need to confirm that is is reproducible on different machine.

**Comment by kaloyan-raev** [comment]
It turns out that Unix is more "humane" than Windows - child processes are not killed when their parent terminates. I found a nice explanation in this article: https://jwhsmith.net/2014/10/unix-child-processes-upon-parent-termination/

The easiest way to reproduce this on Linux or Mac with VSCode is just to kill the VSCode process. Then the PHP language server processes remains burning the CPU at 100%.

**Comment by mniewrzal** [comment]
> The easiest way to reproduce this on Linux or Mac with VSCode is just to kill the VSCode process. 
> Then the PHP language server processes remains burning the CPU at 100%.

Yes, I can reproduce this too.

**Comment by kaloyan-raev** [comment]
I did some debugging and found that the 100% CPU does not happen in the event loop internally, but in the `ProtocolStreamWriter`. On [line 35](https://github.com/felixfbecker/php-language-server/blob/master/src/ProtocolStreamWriter.php#L35) `@fwrite` to the broken parent stream return `0`. On the next line `0 === false` evaluates to false and this repeats forever.

@felixfbecker Can we change this code that when calling `fwrite` result in error, the language server process exits? Perhaps we can do something similar in the `ProtocolStreamReader`?

**Comment by felixfbecker** [comment]
Yep. Actually we just need to remove the `@`, because we now have an error handler and it will throw an `ErrorException`. But unfortunately `0` does not mean error, it just means there were zero bytes written, which would mean we have to keep writing (though we should do that async really and not in a `while`, but that is another issue). Error is indicated indeed by a `false` return value, so not sure what do here? Apparently there is no error, the stream seems to be open, but refuses to get written too.

**Comment by MadHed** [comment]
@felixfbecker @kaloyan-raev 
I found this comment in the php docs. http://php.net/manual/de/function.fwrite.php#96951
So basically, in case of a closed stream fwrite will just keep returning 0 forever and false doesn't really happen unlike what the docs would make us believe :(

I would like to see if we can detect the closed stream via http://php.net/manual/en/function.stream-get-meta-data.php but I will only have time to look into this tomorrow.

**Comment by felixfbecker** [comment]
Sounds like we will have to use a timeout mechanism otherwise. I would also like to make the writing async with `Loop\addWriteStream`. Will probably make all functions async at some point and work with sabre's coroutines and promises. We also need a way to handle responses from client requests async, don't have a solution there atm iirc

**Comment by kaloyan-raev** [comment]
I pushed #110 with a solution that works for me.

**Comment by kaloyan-raev** [comment]
#110 was reverted. Reopening.

**Comment by chergert** [comment]
Another option, is you can `ptrctl()` after you `fork()` with `PR_SET_PDEATHSIG` as it will be preserved across `execve()` causing the child to die with the parent. I'm not sure what happens if the child calls `setsid()` to create a new process group...

I saw this while working on a plugin for `GNOME Builder` this evening, and I just beefed up our process supervisor to try a bit harder to kill the `PHP Language Server` process.

**Comment by felixfbecker** [comment]
@kaloyan-raev Is this issue still relevant?

**Comment by kaloyan-raev** [comment]
I just checked with latest master. It seems the issue is gone.
