### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/php-language-server#176]
@kaloyan-raev @mniewrzal I assume Eclipse Che also uses Docker containers? What can I do to make integration easier?

**Comment by kaloyan-raev** [comment]
Yes, Eclipse Che uses Docker containers. However, language servers do not live in separate Docker containers, but are packed as agents and added to the so called "dev-machine" container that servers the IDE capabilities.

Adding a Dockerfile would not help this in any way.

**Comment by felixfbecker** [comment]
@kaloyan-raev Since you mentioned in #165 that you already tested this in Che, did you manage to run the LS inside a Docker container? I'm having troubles

**Comment by kaloyan-raev** [comment]
Yes, I run the language server in a Docker container. What kind of troubles do you have?

**Comment by felixfbecker** [comment]
I'm testing with a little LSP CLI tool. Locally everything works both over TCP and STDIO. But in a Docker container, it just gives `Unexpected EOF`. In TCP mode, the LS logs `Server listening`, but never `Connection accepted`. I'm stuck on this for hours now.

If you could share your Dockerfile it would be highly appreciated

**Comment by kaloyan-raev** [comment]
In Che the language server is started as a child process and the communication is over STDIO.

The language server is not built in the Docker image, but is installed in the Docker container during startup. Here is the installation script: https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-agent/src/main/resources/agents/scripts/org.eclipse.che.ls.php.script.sh (the interesting part is at the bottom of the script)

The generated `${LS_LAUNCHER}` script file is the one executed when starting the language server. This usually happens when opening some PHP file for the first time.

**Comment by keegancsmith** [comment]
I believe this was resolved by https://github.com/felixfbecker/php-language-server/pull/185

I can use that container via TCP or STDIO. If you pass no arguments it will default to running a TCP server on port 2088. If I just pass `--` as arguments I get STDIO.
