### ISSUE TITLE
Signature help

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/php-language-server#18]
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#signature-help-request

![image](https://user-images.githubusercontent.com/8877998/27498227-53f4ee58-581b-11e7-980d-15aeddd40be6.png)

**Comment by vakata** [comment]
Hello,

I made a very crude attempt at implementing signature help. 

It works well enough for me, but I did not create a PR, because:
1) To improve resolving I had to open the current file and do some seeking
2) I had to resort to using some custom token stacking logic on top of the Lexer class in order to find the active parameter which is an ugly hack and not very elegant.

Still, I thought I'd share, some parts may be useful:
https://github.com/vakata/php-language-server/commits/signatureHelp

**Comment by felixfbecker** [comment]
Open a PR, it's better to discuss it there :)

**Comment by codewp** [comment]
Please let me know when this feature comes to VS Code?
I think that this feature is a most used feature by developers.

Thanks.

**Comment by felixfbecker** [comment]
@codewp there's a subscribe button on the right side
