### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by mindplay-dk** [felixfbecker/php-language-server#226]
I can't tell if the extension is working on not - I can't even tell if the language service is running or not, there is no visual indication in the UI?

I see things like symbol search working, but I haven't really seen auto-completion work at all yet.

For example, [here](https://github.com/mindplay-dk/middleman/blob/master/src/ContainerResolver.php#L48) I get no auto-completion for local properties when I type `$this->`.

When hovering over `container` in `$this->container` in the same file, all I see is `private $container` although this property it type-hinted as `@var ContainerInterface`.

How can I tell if the extension is working?

**Comment by felixfbecker** [comment]
You will have to provide more details. What client are you using? If VS Code, what extension version? You can use whatever method your OS provides to check which processes are running to see if the language server runs (ps, task manager...). In VS Code, the Language Server has a dedicated output channel.

**Comment by mindplay-dk** [comment]
Freshly updated VS Code 1.8.1 and freshly insatlled PHP IntelliSense 0.0.12.

I'm on Win 64 Pro.

> You can use whatever method your OS provides to check which processes are running to see if the language server runs (ps, task manager...).

Yeah, that occurred to me, but there's hundreds of processes and I'm not sure what I'm looking for. The VS Code process had a single child-process, but that was just for the window itself apparently.

> In VS Code, the Language Server has a dedicated output channel.

What's an output channel?

**Comment by Ettemlevest** [comment]
@mindplay-dk output channel: View->Output channel. There you can switch to the PHP Language Server.

**Comment by mindplay-dk** [comment]
Okay, I see the output from the language server, so it's running - it has analysed all source and vendor files, so far so good. But I don't get property type-hints on hover, nor do I get auto-completions...

**Comment by felixfbecker** [comment]
In Windows it will just show a php.exe CLI process with decent CPU and RAM usage.
The inferred type is currently not showing in the hover, see https://github.com/felixfbecker/php-language-server/issues/109
Completion is in latest master of vscode-php-intellisense, but not released because of https://github.com/Microsoft/vscode/issues/16586
If you want to try it out, https://github.com/felixfbecker/php-language-server/pull/165 has some hints.

**Comment by mindplay-dk** [comment]
Okay, so I guess it's working, it just doesn't have the features I was hoping for yet.

I'm closing this issue, but should I maybe open an issue for some kind of visual indication that the language service is running?

TypeScript (for example) has this:

![image](https://cloud.githubusercontent.com/assets/103348/21504831/718f12a8-cc62-11e6-83d3-49308e084279.png)

**Comment by felixfbecker** [comment]
Well in TypeScript there is a valid use case for knowing what compiler version is used because global and local installation can differ, I don't think in PHP that is needed. If there were errors spawning the LS, it would show you an error message. Once we have https://github.com/Microsoft/language-server-protocol/issues/70 there will be more hints in the UI of the LS "working". Please also note that the LS can only do what the protocol provides, any custom UI hints have to be done in the VS Code extension.

**Comment by mindplay-dk** [comment]
> If there were errors spawning the LS, it would show you an error message

That's assuming the plugin launched at all :-)

Maybe on success it could display a notification to let you know it's loaded and running?

I know it may seem unimportant, but without knowing about the "view output" tab, it really isn't easy to find out whether anything is happening or not, and that's confusing.

Alternatively, maybe the README could direct you to the "view output" tab to help you verify that the plugin is installed and doing something?

**Comment by felixfbecker** [comment]
Feel free to open an issue at the plugin repository :)
