### ISSUE TITLE
Initialization fails

### ISSUE THREAD

**Issue by kaloyan-raev** [felixfbecker/php-language-server#4]
1. I have VS Code 1.4.0 on Fedora 24.
2. I installed the PHP IntellSense extension as described: https://github.com/felixfbecker/vscode-php-intellisense#build-and-run-from-source
3. I opened the dev tools in VS Code from Help > Toggle Developer Tools.
4. I opened a PHP file in the editor.

The following error is printed in the Console of Dev Tools:
`[Extension Host] Response handler 'initialize' failed with message: Cannot read property 'code' of null`

**Comment by felixfbecker** [comment]
https://github.com/Microsoft/vscode-languageserver-node/issues/86

**Comment by felixfbecker** [comment]
I added a fix in https://github.com/felixfbecker/php-advanced-json-rpc/commit/f9d7354ada179eea43099859b7fe8fb86b255810 and documentSymbol works now! 🎉

**Comment by kaloyan-raev** [comment]
Yes. It works. So cool! :)

**Comment by kaloyan-raev** [comment]
BTW, I think you should apply the same pattern for JSON serialization everywhere. If an PHP object's member is `null` then it should not be included in the JSON object at all.

I checked the behavior of the Gson library (the most popular for JSON serialization/deserialization in Java) and it does exactly this.

**Comment by felixfbecker** [comment]
@kaloyan-raev Yes, that would be ideal, but not possible in PHP. You cannot find out at serialization time if a property was set to `null` explicitely or if it was simply not set, because in PHP a property is by default `null` if it has not been set. It works in this specific case because the spec says only `error` or `result` should ever be defined, never both, but it won't work for all the structures in the protocol where `null` is actually an accepted value. And it would be a huge amount of work to add the `JsonSerializable` interface everywhere. It would be much nicer if VS Code would just treat `undefined` and `null` the same.

**Comment by kaloyan-raev** [comment]
It is absolutely the same in Java (I am Java developer with some PHP knowledge). This is why I checked how the Gson library handles it.

What about if here: https://github.com/felixfbecker/php-advanced-json-rpc/blob/master/lib/Message.php#L44

instead of 

`return json_encode($this);`

you have

`return json_encode(array_filter((array) $obj));`

Wouldn't be that a universal solution?

**Comment by felixfbecker** [comment]
No, because the spec for example says that the `id` in a response MUST be `null` if there was a parse error parsing the request and the `id` is unknown. It MUST be defined though, because a message without an `id` is considered a notification.

If we did it like this in all protocol structures, there would be no way to serialize actual `null` properties, that have been explicitly set to `null`.

Sidenote: you cannot cast an object directly to an array, it will include private properties. You have to do `get_object_vars()`.

**Comment by kaloyan-raev** [comment]
OK. You are right.

**Comment by felixfbecker** [comment]
I don't like this fact about PHP either. It sucks for ORMs, you have no way to see if a column is `NULL` in the DB or it simply is "unknown" because wasn't eager-loaded / set after construction.
