### ISSUE TITLE
memory leak issue.

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/php-language-server#425]
_From @GaryMeng on June 21, 2017 9:35_

I am using vscode for viewing php project.(Yii2 framework), php intellisense looks work improperly, 
the IDE work slow and memory runs out.

_Copied from original issue: felixfbecker/vscode-php-intellisense#129_

**Comment by felixfbecker** [comment]
Can you share steps to reproduce?

**Comment by mpenna** [comment]
Not sure if they're related or interdependent, but I had to disable the PHP Intellisense extension because this memory leak issue was also happening when I had it enabled. Suddenly vscode would slow down to a complete halt and the whole system would become unresponsive. This happened a couple of times before I eventually noticed in my task manager the PHP process ramping up its memory consumption like crazy. I'm on a Windows 8.1 x64.

**Comment by felixfbecker** [comment]
I would need some code, set of depedencies etc. that reproduces the problem

**Comment by mpenna** [comment]
I'd be glad to, but I'm not sure how to help. From my perspective, it looks like something perhaps time-related, other than any specific PHP project I could be working on. Everytime this happened, if I was fast enough, I would be able to kill the PHP process from the task manager and then everything would go back to normal. Soon after that, though, the leak would reappear. All my PHP projects run inside a Vagrant/Homestead VM, but, as I mentioned, my system's main OS is Windows 8.1, thus all the coding is done "under Windows and the leaky PHP process is the one installed on this system.

**Comment by Slessi** [comment]
Can confirm this happens to me also on macOS Sierra 10.12.5, VSCode 1.14.1

Everything slows down to a halt and I have to actually pull the plug from my machine if I don't manage to kill it in time. Not even quitting VSCode works, have to find it in the process list and manually kill it.

Extensions (Excluding PHP intellisense, had to remove it for now):
![screen shot 2017-07-21 at 14 14 47](https://user-images.githubusercontent.com/3223500/28463101-fcb6e8ca-6e1e-11e7-83e2-68c2367c852c.png)

**Comment by felixfbecker** [comment]
I would love to fix this, but I don't have any way to reproduce this. This language server is running in production on sourcegraph.com and even there I have not seen any memory leak over time:

![image](https://user-images.githubusercontent.com/10532611/28464575-23c7f916-6e26-11e7-9970-4fd4c04244f9.png)

**Comment by Slessi** [comment]
Could it be something else ? To be honest the one time I managed to kill it before my machine became unusable I had htop open and I only saw 2/8Gb RAM usage which was strange - definitely recovered after killing though

**Comment by felixfbecker** [comment]
@Slessi do you know that you can set pass a memory limit as an option? The language server would commit suicide before accidently killing your machine

**Comment by sirber** [comment]
Same thing on Fedora 26. The process usualy takes 350MB RAM. After a few hours working on the same project, the process start using all my memory until my machine crash swapping. Today I was able to kill it. It was using 4.5GB of 8GB total ram.

**Comment by MadHed** [comment]
@felixfbecker Is it possible that a loop in the new parser is not terminating correctly?
I'm currently having a quick look at `Parser.php`

**Comment by carbonacat** [comment]
Hi,

First, thank you for providing this extension. It was really working greatly before that incident!

Same thing is happening to me right now, on Windows 10 (1607), using Wamp's php (php version being 7.1.14) and VSCode (1.15.0).
The memory is drained quickly until the process is eventually killed by Windows.

I've set up a memory limit of 1GB, which effectively kill the language server as soon as it's reached.

This seems to be happening since I updated VSCode a few days ago if that can help?

Also:
- Initial parsing works properly.
- If I don't do anything the language server takes 102.2 MB and do nothing.
- As soon as I try to autocomplete anything, VSCode tells me that "The PHP Language Server crashed 5 times in the last 3 minutes. The server will not be restarted.".
- After which the completion is messed up and just propose everything that looks like a symbol.

My extensions are:
- C/C++ 0.12.2
- C++ Intellisense 0.2.2
- PHP Debug 1.11.1
- PHP IntelliSense 1.5.0

My settings are:
- php.validate.executablePath - "...\\wamp64\\bin\\php\\php7.1.4\\php.exe"
- php.executablePath -  "...\\wamp64\\bin\\php\\php7.1.4\\php.exe"
- php.memoryLimit - "1G"
- php.suggest.basic - false

Logs won't tell much; only that the "Connection got disposed" with a nodejs stacktrace and that .

Hope those information will help you!

**Comment by felixfbecker** [comment]
@carbonacat are you sure it's caused by out-of-memory? Anything in Help > Toggle Developer Tools?

**Comment by carbonacat** [comment]
It's the `php.exe` process that goes out of memory in my case:

(Skipped the 4 first attempts)
```
[Extension Host] PHP process connected
extensionHost.ts:335 [Extension Host] 
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes) in C:\Users\carbonacat\.vscode\extensions\felixfbecker.php-intellisense-1.5.0\vendor\felixfbecker\language-server\src\FqnUtilities.php on line 25

extensionHost.ts:335 [Extension Host] PHP process disconnected
```
