### ISSUE TITLE
Incorrect PHP error when `PHP Intellisense` extension is installed on VSCode

### ISSUE THREAD

**Issue by vboctor** [felixfbecker/php-language-server#544]
In the following function, VS Code shows an `[php] '}' expected.` error and adds a red marker under `p_match`.

```
function test() {
    ...
    return "<a ${t_url_href}${t_url_target}>${p_match[1]}</a>";
}
```

Versions:
- VSCode Version: 1.18.1
- OS Version: MacOS 10.13.1

Doesn't reproduce when running `code --disable-extensions`.

**Comment by felixfbecker** [comment]
Please file on https://github.com/Microsoft/tolerant-php-parser

**Comment by smuuf** [comment]
**Is there any option to hide the errors and warnings that come from the tolerant-php-parser?**

I came upon this today while investigating why *vscode* renders "multiple catch" *(supported since PHP 7.1)* as an error with red squiggles, when I my installed version of PHP is 7.2 ...

After one frustrating hour of trying to disect *"why, oh why"* vscode (probably) uses wrong version of PHP for executing `php -l` *(vscode docs [say]((https://code.visualstudio.com/docs/languages/php#_linting)) this is being used for PHP linting)*, I suddenly realized that I don't have some meticulously hidden old and obscure version of PHP executable somewhere on my disk... but that the error is generated by the *vscode-php-intellisense / php-language-server* - which, I expect, is getting it from the "imperfect" *tolerant-php-parser*.

As I already mentioned, [vscode own docs](https://code.visualstudio.com/docs/languages/php#_linting) say:

> VS Code uses the official PHP linter (php -l) for PHP language diagnostics. **This allows VS Code to stay current with PHP linter improvements.**

I believe the mentioned **advantage *(of having the linting always up-to-date)* is effectively lost**, when errors from external libraries - *which [(as we see)](https://github.com/Microsoft/tolerant-php-parser/issues/103) can not guarantee the same "up-to-date-ness" as the installed PHP binary itself* - are also displayed.

**Is it possible to hide these false-positive "syntax errors"?**

**Comment by cleoni** [comment]
Version 2.3.10 still displays un-existent unclosed curly braces errors (just define a simple class to see).

**Comment by JoabioVilela** [comment]
> A versão 2.3.10 ainda exibe erros inexistentes de chaves não fechadas (apenas defina uma classe simples para ver).

Hello, @cleoni 

Version v2.3.14 still displays un-existent unclosed curly braces errors (just define a simple class to see).

**Joabio Vilela**
PHP Developer
+55 71 9 8693 9939
joabiovilela@gmail.com
[Acesse meu LinkedIn](http://linkedin.com/in/joabiovilela)
[Acesse meu Instagram](https://www.instagram.com/joabiovilela)
[Acesse meu Facebook](https://www.facebook.com/joabiovilela)
