### ISSUE TITLE
Searching for workspace symbols is super slow

### ISSUE THREAD

**Issue by kaloyan-raev** [felixfbecker/php-language-server#91]
This is when calling `Ctrl+T` (Show All Symbols) in VS Code.

I remember it used to return a result in a couple of seconds, but now it keeps searching for a minutes and goes on. I see high CPU usage during this time. Eventually, it may finish, but I haven't got the patient to wait for it.

**Comment by felixfbecker** [comment]
Yes, noticed that too. That is because before we had all ASTs in memory. Now we only have a FQN => URI map. But for SymbolInformations, we need the locations and types of those symbols. So we first apply the query to the FQNs, and then for all FQNs that matched, load the document at the URI and find out the location/type. And because IO in PHP is sync (we could make it async...) it is done in serial. So the less specific your query is, the longer it takes.

I would like to also keep a table of `SymbolInformation`s to speed this up.

**Comment by mniewrzal** [comment]
@felixfbecker Yes, I think having SymbolInformations array would be good compromise between keeping only FQN => URI and ASTs in memory.

**Comment by felixfbecker** [comment]
I will just change the map to FQN => SymbolInformation then because a SymbolInformation includes the URI
